version: '3.8'

services:
  templates-config-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - templates-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - templates-config-api
    restart: unless-stopped
    networks:
      - templates-network
    profiles:
      - production

networks:
  templates-network:
    driver: bridge